<a href="https://colab.research.google.com/github/AKASHPATI007/basic-coding/blob/main/Basic_Coding_Concept.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**STRING**

In [ ]:
# LEN
algo = 'regression'
print(len(algo))

10


In [ ]:
# STRING INDEXING
string = 'JOKER'
print(string[1])
print(string[-1])
print(string[-4])

O
R
O


In [ ]:
# STRING SLICING
print(string[1:5])
print(string[-2:])
print(string[:-1])
print(string[-3:-1])
print(string[1:-1])
            

OKER
ER
JOKE
KE
OKE


In [ ]:
# step size
print(string[1:5:2])
print(string[4:1:-1])
print(string[::-1])
print(string[::-3])
print(string[0::-3])
print(string[1::-3])

OE
REK
REKOJ
RO
J
O


In [ ]:
# lower
a = 'ALGORITHM'
print(a.lower())
A= 'ALGORITHM'
print(A.upper())

algorithm
ALGORITHM


In [ ]:
# Count
a = 'neural network'
print(a.count('ne'))
print(a.count('l'))

2
1


In [ ]:
# find
print(a.find('a'))

4


In [ ]:
# replace
print(a.replace('n','l'))

leural letwork


In [ ]:
# f string
FN = 'Akashpati'
LN = 'Mishra'
print(f"{FN} {LN}")

Akashpati Mishra


**List**

In [ ]:
my_list = ['string', 23 ,100.20, '0' , True]
my_list

['string', 23, 100.2, '0', True]

In [ ]:
# List Indexing
# List Slicing

In [ ]:
# aggregation function
new_list = [2,54,7,5,4,3,45]
print(min(new_list))
print(max(new_list))
print(sum(new_list))
print(sorted(new_list))


2
54
120
[2, 3, 4, 5, 7, 45, 54]


In [ ]:
# Sorted
new_list2 = ['akash', 'Sujain', 'preeti', 'Sabha', 'neha']
print(sorted(new_list2))
print(sorted(new_list2,reverse = True))

['Sabha', 'Sujain', 'akash', 'neha', 'preeti']
['preeti', 'neha', 'akash', 'Sujain', 'Sabha']


In [ ]:
# List Method
# Append
my_list = [1,2,5,4,7,99]
my_list.append(45)
print(my_list)

[1, 2, 5, 4, 7, 99, 45]


In [ ]:
my_list.append([1,4,3])
print(my_list)

[1, 2, 5, 4, 7, 99, 45, [1, 4, 3]]


In [ ]:
# Extend
my_list.extend([11,3,8])
print(my_list)

[1, 2, 5, 4, 7, 99, 45, [1, 4, 3], 11, 3, 8]


In [ ]:
# POp
print(my_list.pop())
print(my_list)


11
[1, 2, 5, 4, 7, 99, 45, [1, 4, 3]]


In [ ]:
print(my_list.pop(4))
print(my_list)

7
[1, 2, 5, 4, 99, 45, [1, 4, 3]]


In [ ]:
# remove()
k_list = [1,2,3,4,5,6,7]
k_list.remove(5)
print(k_list)

[1, 2, 3, 4, 6, 7]


In [ ]:
# clear-- clear the list--
k_list.clear()
k_list

[]

In [ ]:
# count-- returns total occurance of specified element
a_list = [1,2,45,2,5,2,6,8,5,3,3,6,8,'jyoti']
a_list.count(2)

3

In [ ]:
# index()-returns the index of specified element
print(a_list.index(45))
print(a_list.index('jyoti'))

2
13


In [ ]:
#sort() - sort either ascending or descending order
b_list = [4,2,67,45,3,6,8,65,4,3,3]
b_list.sort()
b_list

[2, 3, 3, 3, 4, 4, 6, 8, 45, 65, 67]

In [ ]:
#  reverse()- reverse the list
b_list.reverse()
b_list

[67, 65, 45, 8, 6, 4, 4, 3, 3, 3, 2]

In [ ]:
import array as arr

# creating an integer data type array
x = arr.array('i', [1,2,3,4,5,6,7])


# creatomg a list
y = [8, 9, 10]

# using the fromlist() function
x.fromlist(y)

# Printing the new array
print(x)


array('i', [1, 2, 3, 4, 5, 6, 7, 8, 9, 10])


In [ ]:
x.tolist()
x

array('i', [1, 2, 3, 4, 5, 6, 7])

**Tuples, Sets and Dictionary**

Tuple is immutable

In [ ]:
# use () bracket for tuple
my_tuple = (1,2,3,4,5)
my_tuple

(1, 2, 3, 4, 5)

In [ ]:
# tuple indexing , tuple slicing working is same a string or list working
# remember to see brackets
print(my_tuple[2])

3


In [ ]:
# indexing
my_tuple = (1,2,3,4,5)
my_tuple.index(2)

1

In [ ]:
# Tuple does not support method such as append(), extend(), remove(), pop()

In [ ]:
# zip()
city_list = ['del','pat','cutt','guw']
riv_list = ['yam','ganga','mahanadi','brahmputra']
city_river = list(zip(city_list,riv_list))
print(city_river)

[('del', 'yam'), ('pat', 'ganga'), ('cutt', 'mahanadi'), ('guw', 'brahmputra')]


In [ ]:
# convert to dictionary
dict_1 = dict(city_river)
dict_1

{'del': 'yam', 'pat': 'ganga', 'cutt': 'mahanadi', 'guw': 'brahmputra'}

**SET**

In [ ]:
# empty_set =set()
# non_emppty_set = {1,3,5,'abc'}


In [ ]:
my_list = [1,1,2,4,3,3,2,4,6,5,4,3,3,8,7,6,5,4]
my_set = set(my_list)
my_set

{1, 2, 3, 4, 5, 6, 7, 8}

In [ ]:
# Set can't have mutable item but set is mutable 
my_set = {1,2,[3,4]}
my_set

TypeError: ignored

*Sets Methods*

In [ ]:
# Add
my_set = set()
my_set.add('a')
my_set

{'a'}

In [ ]:
# update-- add multiple element to set
my_set1 = {4,2,6,8}
my_set1.update([2,7,4])
my_set1


{2, 4, 6, 7, 8}

In [ ]:
# Remove()--remove an item or element from set
my_set2 ={2,4,6,8,9,32,5}
my_set2.remove(32)
my_set2

{2, 4, 5, 6, 8, 9}

In [ ]:
# Union()-- Also denoted by '|'
a = {1,2,3,4,5,6}
b = {4,6,87,9,6}
print(a|b)
# or print(a.union(b))

{1, 2, 3, 4, 5, 6, 9, 87}


In [ ]:
# Intersection() --- Also denoted by '&'
a = {1,2,3,4,5,6}
b = {4,6,87,9,6}
print(a&b)
# or print(a.intersection(b))

{4, 6}


In [ ]:
# Difference()---returns difference of two set i.e.(a-b)
a = {1,2,3,4,5,6}
b = {4,6,87,9,6}
print(a-b)
# or print(a.difference(b))

{1, 2, 3, 5}


In [ ]:
# Symmetric Difference--denoted by '^' returns the set of elements in a&b but not in both{ or excluding intersection}
a = {1,2,3,4,5,6}
b = {4,6,87,9,6}
print(a^b)
# print(a.symmetric_difference)

{1, 2, 3, 5, 9, 87}


**Dictionary**

*Dictionary Method*

In [ ]:
marvel_dict = {'name':'thor','place':'asgard','weapon':'hammer',3:'power'}
marvel_dict['place']

'asgard'

In [ ]:
#keys()
list(marvel_dict.keys())

['name', 'place', 'weapon', 3]

In [ ]:
# values()
list(marvel_dict.values())

['thor', 'asgard', 'hammer', 'power']

In [ ]:
# items()
list(marvel_dict.items())

[('name', 'thor'), ('place', 'asgard'), ('weapon', 'hammer'), (3, 'power')]

In [ ]:
# get()-- takes the key as argument & return non if the key is not found in dictionary
print(marvel_dict.get('place'))
print(marvel_dict.get('random','not found'))

asgard
not found


In [ ]:
# update()--
marvel_dict.update({'raj':'simran'})
print(marvel_dict)

{'name': 'thor', 'place': 'asgard', 'weapon': 'hammer', 3: 'power', 'raj': 'simran'}


In [ ]:
marvel_dict['name'] = marvel_dict['name']+' '+ 'rajesh'
print(marvel_dict)

{'name': 'thor rajesh', 'place': 'asgard', 'weapon': 'hammer', 3: 'power', 'raj': 'simran'}


In [ ]:
# dict()-- also create dictionary object from sequence of items which are n pair
country_city_list = [('india','new delhi'),('australia','canberra'),('england','london')]
country_city_dict = dict(country_city_list)
print(country_city_dict)

{'india': 'new delhi', 'australia': 'canberra', 'england': 'london'}


In [ ]:
# pop()- removes & retrun an element from dict hav ing key
country_city_dict.pop('england')

'london'

In [ ]:
country_city_dict

{'india': 'new delhi', 'australia': 'canberra'}

In [ ]:
# zip
name = ['manjeet','nikhil','shambhan']
marks = [40, 50, 60]
mapped = zip(name,marks)
print(mapped)
print(dict(mapped))

{'manjeet': 40, 'nikhil': 50, 'shambhan': 60}


**Statement, Indentation and Condition--**

*Conditional Statement--*



**if, elif,else--**

In [ ]:
'''(if case 1:
  perform action 1
elif case 2:
  perform action 2
else:
  perform action 3 )'''

city = 'pune'
if city == 'delhi':
  print('indian capital')
elif city == 'mumbai':
  print('financial capital')
else:
  print('where are you')

where are you


**Truthy & False--**

A 'Truthy' value will satisfy the check performed by if or while statement. We use 'Truthy' & 'Falsy' to differentiate from the boolean values Truth & False.

All the values are considered 'Truthy' except for the following which is false

"  None--False--0--0.0--an empty set-[ ], { }, ( ),' '  "

In [ ]:
if False:
  print('what do you want')
else:
  print('i have nothing to say')

i have nothing to say


**Loops And Iterations-**


for loop:-

In [ ]:
''' for item in object:
      statement to do stuff '''

got_house = ['stark','tony','rajesh']
for i in got_house:
  print(f"house {i}")


house stark
house tony
house rajesh


**enumerate() function--** requires two iterators index and element

In [ ]:
for number, house in enumerate(got_house):
  print(number+1,house)


1 stark
2 tony
3 rajesh


**range()--** Takes 3 arguments: start, stop, step

In [ ]:
list(range(2,30,2))

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28]

**split()--** if we want to iterate each word in sentence


In [ ]:
heisenburg = 'you are not good enough for me'
print(heisenburg.split())

['you', 'are', 'not', 'good', 'enough', 'for', 'me']


**Tuple unpacking--**

In [ ]:
country_city = [('india','new delhi'),('aus','canbera')]
for country, city in country_city:
  print('the capital of country',country,'is',city)

the capital of country india is new delhi
the capital of country aus is canbera


**While loop--** Statement will repeatedely  execute a single statement or a group of statement as long as condition is true.

Also called "infinite loop"

In [ ]:
x = 0
while x<2:
  print('x is currently:',x)
  x +=1
else:
  print('\n')
  print('all done')

x is currently: 0
x is currently: 1


all done


**break,continue and pass--**

In [ ]:
''' while test:
      code statement
      if test:
        break
      if test:
        continue
    else:

In [ ]:
x=0
while x<10:
  print('x is currently:',x)
  x +=1
  if x==3:
    print('x==3')
    break
  else:
    print('continue')

x is currently: 0
continue
x is currently: 1
continue
x is currently: 2
x==3


In [ ]:
x=['ab','cd']
for i in x:
  i= i.upper()
  print(i)

AB
CD


**List Comprehension**

In [ ]:
'''expression of comprehension'''
'''number**2(output) for number(variable) in list of number(input sequence) if number%2==0(optional predicate)'''

'number**2(output) for number(variable) in list of number(input sequence) if number%2==0(optional predicate)'

In [ ]:
# write first letter of word in another list

words = 'what can i do for you'
first_letter =[ ]
words = words.split()
for word in words:
  
  first_letter.append(word[0])
print(first_letter)

['w', 'c', 'i', 'd', 'f', 'y']


In [ ]:
# by comprehension
first_letter = [word[0] for word in words]
print(first_letter)

['w', 'c', 'i', 'd', 'f', 'y']


In [ ]:
# set comprehension
first_letter = {word[0] for word in words}
print(first_letter)

{'i', 'y', 'w', 'c', 'f', 'd'}


**flipped**

In [ ]:
# Swap the key and values for dictionary
country_city_dict= {'ind':'nd','aus':'can','us':'wdc','eng':'lon'}

flipped = {city:country for country,city in country_city_dict.items()}
print(flipped)

{'nd': 'ind', 'can': 'aus', 'wdc': 'us', 'lon': 'eng'}


**Function and Methods**

In [ ]:
# syntax
'''def example_function(arg1,arg2):
       '''this is where function doc string goes'''
      #do sum stuff
      #return'''

In [ ]:
# write a function which returns the factorial of a number

def factorial(n):
  '''
  function for calculating factorial of number
  '''
  if n<0:
    print('factorial is not defined')
  elif n>0:
   result = 1
  for i in range(1,n+1):
     result = result*i
  else:
    print('the factorial of o is 1')
  return result

factorial(5)

the factorial of o is 1


120

In [ ]:
# above problem by list comprehension
list_of_num = [3,5,6,7,12,4]
factorial_list = [factorial(n) for n in list_of_num]
print(factorial_list)

the factorial of o is 1
the factorial of o is 1
the factorial of o is 1
the factorial of o is 1
the factorial of o is 1
the factorial of o is 1
[6, 120, 720, 5040, 479001600, 24]


In [4]:
# Write a function which add an element to a list. This function takes the list as an argument and the element to be added

height = [172,191,187,154]

def list_append(my_list,elem):
  '''
  This function append an element to the list
  '''
  new_list = my_list + [elem]
  return new_list

print(height)
print(list_append(height,187))
print(height)


# Note- It will not change my original list where as if we use list.append(187) the it will changed my originnal list

[172, 191, 187, 154]
[172, 191, 187, 154, 187]
[172, 191, 187, 154]


**Production Grrade Programming:-**

Class- Users defined objects are created using class keywords.

Attributes- Is a characterstics of an objects

Method- is an operation we can perform with object syntax for creating attributes


In [13]:
# Creating a class circle

class Circle():
 def __init__(self,radius=1):
  self.radius = radius
  self.area = 3.14*radius*radius

 def Circumference(self):
  return 2*3.14*self.radius

C = Circle()
print(C.area)
print(C.Circumference)


3.14
<bound method Circle.Circumference of <__main__.Circle object at 0x7f7097aca7d0>>


**Polymorphism:-**Way in which different object classes can share the same method name and those method can be called from same place even thorugh variety of different object might be posses in.

In [20]:
class housestark:
  def __init__(self,sigil):
    self.sigil = sigil

  def motto(self):
    return"House stark with sigil"+' ' +self.sigil+' '+ "has the motto 'winter is coming'"

class houselanister:
  def __init__(self,sigil):
    self.sigil = sigil
  def motto(self):
    return "hpuse lanister with sigil"+' ' + self.sigil+ "has the motto'hear me roar"

arya = housestark('direwolf')
tyrion = houselanister('golden lion')

print(arya.motto())

House stark with sigil direwolf has the motto 'winter is coming'


**Error Ans Exception Handling-**

In [22]:
# try and Except--mainly used to handling errors

try:
  print('good to go')
  print(jnn)
except:
  print('oops!')



good to go
oops!


**Finally**-If we want to run our code after exception occured. this is where finally comes.

In [25]:
a =1
b = 0.2

try:
  print(hjbjbnj,type(hjbjbnj))
except:
  print(b,type(b))
finally:
  print('type printed')

0.2 <class 'float'>
type printed


**NumPy Operations:-**

Different ways of creating ndarray:-

In [26]:
import numpy as np
# Uninitialized
uninitialised_array = np.empty([2,3],dtype=int)
print(uninitialised_array)

[[58607280        0        0]
 [       0        0        0]]


In [29]:
# Initialized with zero
zero_array = np.zeros((3,3))
print(zero_array)

# Another array
another_zero_array = np.zeros((4,3))
print(another_zero_array)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [31]:
# Initialized with ones
ones_array = np.ones((2,3),dtype=int)
print(ones_array)

[[1 1 1]
 [1 1 1]]


In [33]:
# Array from numerical ranges
array_with_ranges = np.arange(5)
print(array_with_ranges)
print(np.arange(10,20,2))

[0 1 2 3 4]
[10 12 14 16 18]


In [36]:
# to get the number of evenly spaced values between intervals
# parameter for the function- np.linspace(start,stop,num,endpoint,retstep,dtype)

linearly_space_value = np.linspace(10,20,9,endpoint=False,retstep=True)
linearly_space_value

(array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
        15.55555556, 16.66666667, 17.77777778, 18.88888889]),
 1.1111111111111112)

In [38]:
# array from randon number
random_array = np.random.random((4,3))
random_array

array([[0.57966095, 0.36847061, 0.09514303],
       [0.19110444, 0.01833816, 0.38731167],
       [0.0126919 , 0.42472766, 0.211028  ],
       [0.0054695 , 0.38291197, 0.9125157 ]])

In [39]:
# get array with random input integral of desired shape
# np.full(start,end,size)
random_i_arr = np.random.randint(0,5,size=(2,3,4))
random_i_arr

array([[[2, 0, 1, 0],
        [0, 1, 2, 4],
        [2, 0, 0, 3]],

       [[1, 1, 1, 2],
        [3, 1, 0, 0],
        [2, 0, 1, 3]]])

In [41]:
# array with specified number
# to get array with specified input element of desired shape
# np.full(shape,value)
a = np.full((3,3),30)
a

array([[30, 30, 30],
       [30, 30, 30],
       [30, 30, 30]])

In [42]:
# to get identity matrix
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

**Creating ndarray with existing data**

In [43]:
# List to ndarray
list = [1,2,3]
np.asarray(list)


array([1, 2, 3])

In [44]:
# tuple to ndarray
tuple = (1,2,3)
np.asarray(tuple)

array([1, 2, 3])

In [47]:
# one dimentional array of some PN
print(np.array([2,3,5,7]))
print('-------------------')
# 2-D array
print(np.array([[1,2],[3,4]]))
print('------------------')
# 3-D array
print(np.array([[[1,2],[3,4]],[[5,6],[7,8]]]))

[2 3 5 7]
-------------------
[[1 2]
 [3 4]]
------------------
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


**Array Inspection**
1. ndarray.shape-gives shape
2. ndarray.ndim- returns no. of array dimentions
3. ndarray.size- returns total no. of elements in array
4. ndarray.dtype- returns data type of an array
5. ndarray.size-

In [52]:
# ndarray.shape
alma = np.array([[[1,2,3],[2,3,5]],[[4,5,5],[6,7,6]]])
print(alma.shape)
print(alma.ndim)
print(alma.size)
print(alma.dtype)


(2, 2, 3)
3
12
int64


In [54]:
# np.astype() --Change data type of an array to float

aravali = np.array([2,3,4])
print(aravali.dtype)
aravali = aravali.astype('float64')
print(aravali.dtype)

int64
float64


In [55]:
# np.insert--To insert item to array

a = np.random.randint(10,20,(2,3,3))
print(a)
print('-------------------------------')
print(np.insert(a,0,100,0))
print('-------------------------------')
print(np.insert(a,0,100,2))
print('-------------------------------')
print(np.insert(a,0,100,1))

[[[15 11 16]
  [12 12 13]
  [10 15 12]]

 [[17 10 19]
  [10 19 10]
  [10 13 17]]]
-------------------------------
[[[100 100 100]
  [100 100 100]
  [100 100 100]]

 [[ 15  11  16]
  [ 12  12  13]
  [ 10  15  12]]

 [[ 17  10  19]
  [ 10  19  10]
  [ 10  13  17]]]
-------------------------------
[[[100  15  11  16]
  [100  12  12  13]
  [100  10  15  12]]

 [[100  17  10  19]
  [100  10  19  10]
  [100  10  13  17]]]
-------------------------------
[[[100 100 100]
  [ 15  11  16]
  [ 12  12  13]
  [ 10  15  12]]

 [[100 100 100]
  [ 17  10  19]
  [ 10  19  10]
  [ 10  13  17]]]


**Slicing Operations--**

In [56]:
# slicing 1-D array
a = np.arange(10)
print(a)
print(a[2:5])

array([2, 3, 4])

In [67]:
# slicing 2-D array
b = np.random.randint(2,9,(3,3))
print(b)
print('---------------------')
print(b[0:2])


[[8 4 6]
 [3 5 4]
 [4 6 7]]
---------------------
[[8 4 6]
 [3 5 4]]
---------------------
[]


In [69]:
b = np.random.randint(2,9,(3,3))
print(b)
print('---------------------')
print(b[0:2,-2:])

[[2 8 4]
 [7 2 8]
 [5 5 6]]
---------------------
[[8 4]
 [2 8]]


In [70]:
# slicing 3-D array
c = np.random.randint(2,7,(3,2,2))
print(c)
print('-----------')
print(c[0:2,1:,1:])

[[[3 3]
  [2 3]]

 [[5 5]
  [2 4]]

 [[4 6]
  [4 6]]]
-----------
[[[3]]

 [[4]]]


**array manipulations--**

1. np.tanspose(array)- to transpose array
2. np.reshape(array,shape)-to change shape of an array(2x3--3x2 but not(3x4)
3. np.resize(array,shape)-to return new array with shape(3x2--2x3--2x5)
4. np.flatten(array)-to flatten the array

In [75]:
a = np.random.randint(2,7,(2,3))
print(a)
print('--------------')
print(np.transpose(a))
print('--------------')
print(np.reshape(a,(3,2)))
print('--------------')
print(np.resize(a,(3,5)))
print('--------------')
print(a.flatten())


[[2 6 2]
 [6 4 6]]
--------------
[[2 6]
 [6 4]
 [2 6]]
--------------
[[2 6]
 [2 6]
 [4 6]]
--------------
[[2 6 2 6 4]
 [6 2 6 2 6]
 [4 6 2 6 2]]
--------------
[2 6 2 6 4 6]
